version: '3'
services:
  oereb-db:
    image: ghcr.io/oereb/oereb-db:2
    environment:
      POSTGRES_DB: oereb
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_HOST_AUTH_METHOD: md5
      PG_WRITE_PWD: ddluser
      PG_READ_PWD: dmluser
      PG_GRETL_PWD: gretl
    ports:
      - "54323:5432"
